### PR TITLE
fix issue #40: make internal message queues unlimited

### PR DESCRIPTION
**Pull request by niamster**

### CODE REVIEW

**Comment by tarcieri** [comment]
Seems ok, but keep this in mind:

https://twitter.com/mrb_bk/status/395301262238838784

**Comment by digitalextremist** [comment]
Under what circumstances do we need this?

**Comment by niamster** [comment]
@tarcieri I totally agree though I don't see a better way to fix this. Maybe before sending an IPC message check the queue status and reschedule. I don't know whether this will work as the reader and writer are in the same celluloid context if I understand correctly.

@digitalextremist we can though we need a mechanism to fix the deadlock w/o throwing exception "stop producing too many work".

**Comment by niamster** [comment]
In fact the root cause of the deadlock is that celluloid holds a mutex while calling reactor.wakeup.
Does it make sense to call wake under the lock? I'll create another issue on celluloid side to raise discussion.

**Comment by tarcieri** [comment]
@niamster the general idea of this sort of wakeup system is it should be possible to wake up the loop even though another thread is holding the lock. If not, it's a bug

**Comment by niamster** [comment]
The real issue is celluloid/celluloid#500

**Pull request closed without merging**
