### PR TITLE
This ports Celluloid::ZMQ to CZTop

### PR DESCRIPTION
**Pull request by paddor**
Almost identical code changes, but with conflicts resolved.

### CODE REVIEW

**Comment by chuckremes** [comment]
@paddor I promise to review tomorrow. Ran out of time today. Thank you for fixing conflicts and opening a new PR.

**Comment by paddor** [comment]
CI fixed. It now doesn't need `sudo` on Travis anymore, just builds libzmq and libczmq from master, using ccache to keep it kinda speedy. It uses the installation scripts of czmq-ffi-gen, just like CZTop itself does. I know this is an additional dependency, but if this is not desired, we can just copy the 2 shell scripts into this repository, or find another solution. As far as I can remember, Travis doesn't offer recent versions of zmq/czmq on their VMs, that's why we have to build them from master.

The supported rubies in `.travis.yml` have been adapted/updated.

JRuby fails because of `java.lang.OutOfMemoryError`. See [here](https://travis-ci.org/paddor/celluloid-zmq/jobs/139077829).

Sorry for the commit mess.

**Comment by digitalextremist** [comment]
Removing the `sudo` dependency is *awesome* in and of itself. Will comment further soon, but just wanted to jump on that piece for the time being. So awesome.

**Comment by paddor** [comment]
Yeah, I was happy to get rid of this dependency from cztop/czmq-ffi-gen back then too. :)

I just realized the caching might not actually be working... maybe I need to add

```cache:
  directories:
    - $HOME/.ccache
    - $HOME/.bundle
```
to `.travis.yml`.

**Comment by chuckremes** [comment]
@digitalextremist This looks good to me. Okay to merge?

**Comment by digitalextremist** [comment]
Yep! All you; go for it @chuckremes. Will pull and tweak right now after you do.

**Comment by chuckremes** [comment]
@paddor Thanks for your awesome code.

**Comment by paddor** [comment]
You're very welcome. It's my pleasure to see this happening!

**Comment by Taher-Ghaleb** [comment]
Hello,

Sorry, I know it's been a long time ago, but I am curious why caching hasn't been enabled before this (i.e., since December 17, 2014, when it became available to open source projects).

Thank you.

**Comment by digitalextremist** [comment]
@Taher-Ghaleb we are long-range innovators more than maintainers of lock-step with this protocol.

In fact, most of us who met surrounding this gem are thinking in `RINA` terms, and going between `Ruby` and `Crystal` looking for the right insertion point for the next set of capabilities.

You are _more than welcome_ to submit a very simple PR on this for the people still using this gem.

**Pull request merged**
